# Generated by Django 3.1.7 on 2021-05-08 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0004_auto_20210508_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publication',
            new_name='post_date',
        ),
    ]
