# Generated by Django 3.1.7 on 2021-06-07 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0012_auto_20210604_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='facebool_url',
            new_name='facebook_url',
        ),
    ]
